version: "3.8"
volumes:
  psql:
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: atomhacks
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432