version: "3.8"
volumes:
  mysql:
services:
  db:
    image: mysql:8.2
    environment:
      MYSQL_DB: atomhacks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 5432:5432
