import type { Metadata } from 'next'
import React from 'react';
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* Puting the Navbar here allows it to be replicated across all pages, including
      the main page and the gallery page. Think of this as a template for all pages.*/}
      <body className={inter.className}>
      <Navbar />
        {children}</body>
    </html>
  )
}
